update all tools, etc
git-svn-id: file:///source/coreland/installer/trunk@2931 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/UNIT_TESTS/mk-cctype b/UNIT_TESTS/mk-cctype
--- a/UNIT_TESTS/mk-cctype
+++ b/UNIT_TESTS/mk-cctype
@@ -1,4 +1,5 @@
 #!/bin/sh
+# $Id: mk-cctype 2909 2007-12-12 21:21:47Z m0 $
 
 cleanup()
 {
@@ -12,16 +13,37 @@ then
   exit 1
 fi
 
-( cat <<EOF
+#
+# If conf-x-cctype exists, compiler is attempting to cross compile and
+# the compiler cannot be assumed to output executables compatible with
+# this system.
+#
+
+if [ -f conf-x-cctype ]
+then
+  TYPE=`head -n 1 conf-x-cctype`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-x-cctype" 1>&2
+    cleanup
+    exit 1
+  fi
+  echo "${TYPE}"
+else
+  ( cat <<EOF
 #include <stdio.h>
-const char *var = "UNKNOWN";
+const char *var;
 int main()
 {
+  var = "UNKNOWN";
+#if defined(__BORLANDC__)
+  var = "BORLAND_CXX";
+#endif
 #if defined(__TURBOC__)
   var = "BORLAND_TURBO_C";
 #endif
-#if defined(__BORLANDC__)
-  var = "BORLAND_CXX";
+#if defined(__MWERKS__)
+  var = "CODEWARRIOR";
 #endif
 #if defined(__COMO__)
   var = "COMEAU_CXX";
@@ -53,17 +75,17 @@ int main()
 #if defined(__ghs__)
   var = "GREENHILL";
 #endif
-#if defined(__HP_cc)
-  var = "HP_C";
-#endif
 #if defined(__HP_aCC)
   var = "HP_ACC";
 #endif
-#if defined(__xlC__) || defined(__IBMC__) || defined(__IBMCPP__)
-  var = "IBM_XL";
+#if defined(__HP_cc)
+  var = "HP_C";
 #endif
 #if defined(__IAR_SYSTEMS_ICC__)
   var = "IAR";
+#endif
+#if defined(__xlC__) || defined(__IBMC__) || defined(__IBMCPP__)
+  var = "IBM_XL";
 #endif
 #if defined(__INTEL_COMPILER) || defined(__ICC) || defined(__ECC) || defined(__ICL)
   var = "INTEL";
@@ -71,14 +93,14 @@ int main()
 #if defined(__KCC)
   var = "KAI";
 #endif
-#if defined(__CA__) || defined(__KEIL__)
-  var = "KEIL_CARM";
-#endif
 #if defined(__C166__)
   var = "KEIL_C166";
 #endif
 #if defined(__C51__) || defined(__CX51__)
   var = "KEIL_C51";
+#endif
+#if defined(__CA__) || defined(__KEIL__)
+  var = "KEIL_CARM";
 #endif
 #if defined(__LCC__)
   var = "LCC";
@@ -89,8 +111,8 @@ int main()
 #if defined(__HIGHC__)
   var = "METAWARE";
 #endif
-#if defined(__MWERKS__)
-  var = "CODEWARRIOR";
+#if defined(_MRI)
+  var = "MICROTEC";
 #endif
 #if defined(__MINGW32__)
   var = "MINGW32";
@@ -101,12 +123,6 @@ int main()
 #if defined(__MRC__) || defined(MPW_C) || defined(MPW_CPLUS)
   var = "MPW";
 #endif
-#if defined(_MSC_VER)
-  var = "VISUAL_CXX";
-#endif
-#if defined(_MRI)
-  var = "MICROTEC";
-#endif
 #if defined(__CC_NORCROFT)
   var = "NORCROFT";
 #endif
@@ -115,6 +131,9 @@ int main()
 #endif
 #if defined(_PACC_VER)
   var = "PALM";
+#endif
+#if defined(__PCC__)
+  var = "PCC";
 #endif
 #if defined(__POCC__)
   var = "PELLES";
@@ -155,6 +174,9 @@ int main()
 #if defined(__USLC__)
   var = "USL_C";
 #endif
+#if defined(_MSC_VER)
+  var = "VISUAL_CXX";
+#endif
 #if defined(__WATCOMC__)
   var = "WATCOM";
 #endif
@@ -163,26 +185,26 @@ int main()
 }
 EOF
 ) > _mk_cctype.c
-
-if [ $? -ne 0 ]
-then
-  echo "fatal: could not create _mk_cctype.c" 1>&2
-  cleanup
-  exit 1
-fi
-${SYS_CC} -o _mk_cctype _mk_cctype.c
-if [ $? -ne 0 ]
-then
-  echo "fatal: could not create _mk_cctype" 1>&2
-  cleanup
-  exit 1
-fi
-./_mk_cctype
-if [ $? -ne 0 ]
-then
-  echo "fatal: could not create _mk_cctype" 1>&2
-  cleanup
-  exit 1
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not create _mk_cctype.c" 1>&2
+    cleanup
+    exit 1
+  fi
+  ${SYS_CC} -o _mk_cctype _mk_cctype.c
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not create _mk_cctype" 1>&2
+    cleanup
+    exit 1
+  fi
+  ./_mk_cctype
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not execute _mk_cctype" 1>&2
+    cleanup
+    exit 1
+  fi
 fi
 
 cleanup
